[workspace]
resolver = "2"

members = [ "cli", "catalog", "firehose-client", "idl-decoder", "scheduler"]

[workspace.dependencies]
firehose-client = { path = "firehose-client" }
idl-decoder = { path = "idl-decoder" }
catalog = { path = "catalog" }
